### ISSUE TITLE
사이드바 컴포넌트 개발

### ISSUE THREAD

**Issue by kangsiwoo** [Bto10/BTO_Clinet#6]
## ✨ 개요
sideBar 컴포넌트 개발

## ✅ 해야 할 일
sideBar 컴포넌트 퍼블리싱

## 🙏🏻 요구사항
화이팅

## 🙋🏻 덧붙일 말
빠른 개발 부탁합니다

**Comment by noahmik** [comment]
App.js 부분 머지할때 재현님한테 말 해주세요
